library(ggplot2)
library(dplyr)
library(reshape2)

library(purrr)

# Get the lengths of each data frame in combo_list
# combo_list is generated by code in supplement B3 code 12
combo_lengths <- map_int(combo_list, nrow)

print(combo_lengths)

topic_matrix <- matrix(NA, nrow = 20, ncol = 20)

for (name in names(combo_lengths)) {
  topics <- as.numeric(unlist(strsplit(gsub("Combo_topic_", "", name), "_")))
  topic_matrix[topics[1], topics[2]] <- combo_lengths[[name]]
  topic_matrix[topics[2], topics[1]] <- combo_lengths[[name]]  # Ensure symmetry
}

topic_labels <- td_gamma %>% group_by(topic) %>% slice(1) %>% select(labels)

rownames(topic_matrix) <- topic_labels$labels
colnames(topic_matrix) <- topic_labels$labels

heatmap_data <- melt(topic_matrix, varnames = c("Topic1", "Topic2"), value.name = "Length")


upper_triangle_data <- heatmap_data %>%
  filter(as.numeric(factor(Topic1)) < as.numeric(factor(Topic2))) %>% 
  mutate(Number_of_papers = Length/2)

# Create the heatmap with only the upper triangle
heatmap <- ggplot(upper_triangle_data, aes(x = Topic1, y = Topic2, fill = Length)) +
  geom_tile() +
  # Adjust the gradient to make the highest values less dark (medium gray)
  scale_fill_gradient(low = "white", high = "gray30", na.value = "white") +
  geom_text(aes(label = Number_of_papers), color = "black", na.rm = TRUE, size = 2) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    panel.grid = element_blank(),
    plot.title = element_text(size = 2.5*2.8),
    axis.text = element_text(size = 2.5*2.8), 
    axis.title = element_text(size = 2.5*2.8),
    legend.position = "none") +
  labs(x = "Topic", y = "Topic", caption = "Number of papers using both topics \n(at least 10% of vocabulary from both topics )")

ggsave("supplements_for_submission/figure5_heatmap_of_topic_combinations.pdf", plot = heatmap, device = cairo_pdf, width = 7, height = 5, dpi = 300)

